version: '3.8'

services:
  weather-app:
    build:
      context: .          # La root va bene perché sia Dockerfile che meteo2 sono lì
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - API_KEY=YOUR_API_KEY